FROM ghcr.io/rocker-org/devcontainer/geospatial:4.5

RUN install2.r --error languageserver && \
    installGithub.r nx10/httpgd

# Missing libraries
RUN apt-get install --no-install-recommends -y libglpk-dev

RUN apt-get update && apt-get install -y --no-install-recommends vim

RUN quarto install tinytex 

# RUN tlmgr update --self --all

CMD ["bash"]
